[package]
name = "zero-shell"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27"
chrono = { version = "0.4", default-features = false, features = ["clock"], optional = true }

[features]
humantime = ["dep:chrono"]
